/**
 * Case study — French AI Learning App.
 *
 * Public, recruiter-facing deep dive on the private French learning
 * web app. The page is structured to be skimmed in 30 seconds (hero
 * + workflow) and then read in 3 minutes (decisions, production
 * concerns, transferable workflow).
 *
 * Shared building blocks (cards, steps, stack box, screenshot slot)
 * live in components/case-study.tsx — keep new ones there too.
 * Inline-only components below are the page-specific bits:
 * BeforeAfterSlot (the hero pair) and DemoVideo (phone recording).
 */

import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import {
  ArrowLeft,
  Camera,
  Sparkles,
  FileText,
  BookOpenCheck,
  Printer,
  Mail,
  Github,
  Linkedin,
  Shield,
  ScanLine,
  Database,
  Eye,
  FileDown,
} from "lucide-react";
import { Hairline, Section } from "@/components/section";
import { CopyButton } from "@/components/copy-button";
import { ProjectMeta } from "@/components/project-meta";
import {
  IconCard,
  ImageSlot,
  NumberedStep,
  StackBox,
  TitleBodyCard,
} from "@/components/case-study";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "French AI Learning App · Case Study · Jakub Sykulski",
  description:
    "Handwritten classroom notes → structured vocabulary cards via Gemini. A case study in AI-assisted product prototyping.",
  robots: { index: false, follow: false },
};

const CV_SUMMARY = `AI-assisted Learning & Knowledge Workflow Prototype
Designed and built a private AI-assisted web application that converts scanned French classroom notes into structured vocabulary cards, explanations and print-ready revision materials using the Gemini API. Defined the product workflow, data model and prompt architecture; implementation was AI-assisted with Cursor, Claude Code and Codex on Next.js, FastAPI and Supabase. The underlying scan-to-structured-knowledge pipeline is directly transferable to claims intake, meeting notes and policy-document processing.`;

export default function CaseStudy() {
  return (
    <main className="mx-auto max-w-5xl px-6 py-10 md:px-10 md:py-16">
      {/* ── Back link ─────────────────────────────────────────────── */}
      <Link
        href="/"
        className="inline-flex items-center gap-1.5 text-sm font-medium text-stone-600 transition hover:text-stone-900"
      >
        <ArrowLeft className="h-4 w-4" />
        Back to portfolio
      </Link>

      {/* ── Hero ──────────────────────────────────────────────────── */}
      <header className="mt-10">
        <p className="text-[0.78rem] font-bold uppercase tracking-[0.14em] text-stone-500">
          Case study · Education · Knowledge workflows
        </p>
        <h1 className="shimmer mt-4 font-display text-[clamp(2.25rem,6.5vw,4.25rem)] font-extrabold leading-[1.05] tracking-tight">
          Turning handwritten classroom notes
          <br />
          into structured learning material.
        </h1>
        <p className="mt-5 max-w-3xl text-[17px] leading-[1.7] text-stone-700 md:text-lg">
          A private web app that scans French classroom notes and returns
          clean vocabulary cards, grammar explanations, conjugation tables and
          print-ready revision sheets, generated by the Gemini API and
          stored as structured, reusable data.
        </p>

        <div className="mt-6 flex flex-wrap gap-3">
          <a
            href={site.demoMailto("French AI Learning App")}
            className="inline-flex items-center gap-2 rounded-xl bg-accent-deep px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-accent-darker"
          >
            <Mail className="h-4 w-4" />
            Request demo access
          </a>
          <a
            href="#architecture"
            className="inline-flex items-center gap-2 rounded-xl border border-stone-300/70 bg-white/60 px-4 py-2 text-sm font-semibold text-stone-700 transition hover:bg-white"
          >
            Jump to architecture
          </a>
        </div>

        {/* Phone-recorded demo: the actual lifecycle — handwritten
            page on the desk, photo taken in-app, scan-card returned.
            Autoplays muted on loop; mobile recruiters see motion
            within the first viewport. */}
        <DemoVideo />
      </header>

      <ProjectMeta
        rows={[
          { label: "Timeline", value: "Sept 2025 – present" },
          { label: "Role", value: "Product · data model · prompt design · AI integration" },
          { label: "Stack", value: "Next.js · FastAPI · Supabase · Gemini" },
          { label: "Users", value: "Personal coursework tool · tested with classmates" },
          { label: "Status", value: "Working prototype · in daily use" },
        ]}
      />

      <Hairline />

      {/* ── The problem ──────────────────────────────────────────── */}
      <Section eyebrow="Context" title="The problem">
        <div className="grid gap-6 text-[16px] leading-[1.75] text-stone-700 md:grid-cols-3">
          <p>
            Handwritten notes are messy: vocabulary is scattered across
            margins, grammar rules mix with examples, and translations live
            on a different page than the words they explain.
          </p>
          <p>
            Building clean revision material by hand is a 20-minute chore
            after every class, exactly when motivation is lowest. Most
            learners skip it. So do their classmates.
          </p>
          <p>
            The app removes the chore: photograph the page, choose what to
            extract, and get a structured card back in seconds: searchable,
            printable, and shareable with the class group.
          </p>
        </div>
      </Section>

      {/* ── Workflow ─────────────────────────────────────────────── */}
      <Section eyebrow="How it works" title="The workflow">
        <ol className="grid grid-cols-1 gap-4 md:grid-cols-5">
          <NumberedStep tone="accent" n={1} icon={<Camera className="h-5 w-5" />} label="Photo" sub="Mobile or desktop upload" />
          <NumberedStep tone="accent" n={2} icon={<Sparkles className="h-5 w-5" />} label="Gemini" sub="Multi-focus extraction" />
          <NumberedStep tone="accent" n={3} icon={<FileText className="h-5 w-5" />} label="Structured JSON" sub="Validated server-side" />
          <NumberedStep tone="accent" n={4} icon={<BookOpenCheck className="h-5 w-5" />} label="Stored card" sub="Searchable, shareable" />
          <NumberedStep tone="accent" n={5} icon={<Printer className="h-5 w-5" />} label="Revise / print" sub="Spaced repetition ready" />
        </ol>
      </Section>

      {/* ── Before / After — static proof for skimmers who can't or
           won't play the hero video. Same notes, same morning. */}
      <Section eyebrow="The same notes, the same morning" title="Before / after">
        <div className="grid grid-cols-1 items-start gap-6 md:grid-cols-2">
          <BeforeAfterSlot
            kind="before"
            caption="A page of handwritten French class notes, as the learner brings it in."
          />
          <BeforeAfterSlot
            kind="after"
            caption="The structured vocabulary card the app returns, ready for revision."
          />
        </div>
      </Section>

      {/* ── Product tour ─────────────────────────────────────────── */}
      <Section eyebrow="The product" title="What it does">
        <div className="grid grid-cols-1 items-start gap-6 md:grid-cols-2">
          <ImageSlot
            baseDir="french-ai"
            sizes="(min-width: 768px) 50vw, 100vw"
            label="Home"
            caption="Three entry points: weekly course path, revision library, scanner. The big calm title is on purpose: most learning apps shout, this one breathes."
            filename="home.jpg"
            width={1309}
            height={997}
            alt="Home dashboard of the French learning app with three large tiles linking to weekly course path, revision library and scanner."
          />
          <ImageSlot
            baseDir="french-ai"
            sizes="(min-width: 768px) 50vw, 100vw"
            label="Weekly course path"
            caption="Each week opens to its sections in order, printable in one click. Scanned fiches attach to the week they belong to, so revision stays close to the lesson."
            filename="parcours.jpg"
            width={1314}
            height={1272}
            alt="Weekly course path view showing the active week's sections, attached scanned fiches and printing controls."
          />
        </div>
      </Section>

      {/* ── Decisions ────────────────────────────────────────────── */}
      <Section eyebrow="The hard parts" title="Decisions & trade-offs">
        <div className="grid grid-cols-1 gap-5 md:grid-cols-2">
          <TitleBodyCard
            title="Gemini over OpenAI"
            body="Gemini 2.5 and 3 handle multimodal input (image + text) natively with structured JSON output via response_schema. Cheaper per call at our volume, and the schema-enforced output meant less brittle parsing on the backend."
          />
          <TitleBodyCard
            title="response_schema, not free-text JSON"
            body="Free-text JSON output drifts: keys disappear, types change. Forcing Gemini through a strict schema kills that whole class of bugs and acts as a second line of defence against prompt injection (the model can't easily exfiltrate fields that aren't in the schema)."
          />
          <TitleBodyCard
            title="Typed content blocks, not MDX"
            body="Course content lives as typed JSON blocks (heading, paragraph, vocab, example, quiz), not freeform Markdown. Editors stay safe, admin UI can render previews, and the same blocks render to mobile, print, and revision in three styles."
          />
          <TitleBodyCard
            title="FastAPI, not Next.js API routes"
            body="The AI pipeline (image validation, Gemini calls, post-processing) is enough work that I wanted a typed Python service with proper test coverage, separate from the UI deploy. Render auto-deploys the backend; Vercel handles the frontend. Two failure modes, isolated."
          />
          <TitleBodyCard
            title="Multi-focus, not one-shot"
            body="Users pick which sections they want (vocabulary, grammar, conjugation, translation). Each focus is an independent extraction with its own validation. Smaller prompts, better focus quality, and one focus failing doesn't sink the whole scan."
          />
        </div>
      </Section>

      {/* ── Production-aware prototyping ─────────────────────────── */}
      <Section
        eyebrow="What sets this apart"
        title="Production-aware prototyping"
      >
        <p className="max-w-3xl text-[16px] leading-[1.75] text-stone-700">
          Most AI-assisted prototypes ship the happy path and call it done.
          This one was built for my own daily coursework and tested with
          classmates during the course, which meant treating security,
          observability and dependency hygiene as first-class concerns,
          not afterthoughts.
        </p>
        <ul className="mt-8 grid grid-cols-1 gap-5 md:grid-cols-2">
          <IconCard
            icon={<Shield />}
            title="Defence in depth against prompt injection"
            body="Three layers in the Gemini pipeline: a security directive at the top of the system prompt, response_schema constraining output shape, and URL redaction against an allowlist before content reaches the model. Each layer can fail and the others still catch the attack."
          />
          <IconCard
            icon={<ScanLine />}
            title="Image validation by magic bytes"
            body="Uploaded images are checked by magic bytes, not the multipart Content-Type the browser claims. Anything not in the explicit allowlist (PNG, JPEG, HEIC, WebP) is rejected, then re-encoded through Pillow before reaching the AI. Polyglot files don't get past the gate."
          />
          <IconCard
            icon={<Database />}
            title="Row Level Security as fallback"
            body="The backend uses Supabase service-role and filters by user at the service layer. Row Level Security at the Postgres layer is enabled regardless, so a leaked anon key, or a future direct PostgREST hit, still can't cross user boundaries."
          />
          <IconCard
            icon={<Eye />}
            title="Observability + dependency audit in CI"
            body="Logfire spans on every request, Sentry on uncaught errors with PII off. CI runs pip-audit on every backend build and npm ci --ignore-scripts to defuse postinstall worms. Dependabot opens PRs weekly; major bumps stay manual."
          />
        </ul>
      </Section>

      {/* ── Architecture ─────────────────────────────────────────── */}
      <Section
        eyebrow="Architecture"
        title="Stack"
        className="scroll-mt-12"
      >
        <div id="architecture" className="grid grid-cols-2 gap-5 md:grid-cols-4">
          <StackBox label="Frontend" items={["Next.js 16", "TypeScript", "Tailwind 4"]} />
          <StackBox label="Backend" items={["FastAPI", "Python 3.12", "Pydantic v2"]} />
          <StackBox label="Data & auth" items={["Supabase Postgres", "Row Level Security", "Postgres FTS"]} />
          <StackBox label="AI" items={["Gemini 2.5 / 3", "response_schema", "Multi-focus prompts"]} />
          <StackBox label="Deploy" items={["Vercel (FE)", "Render (BE)", "Cloudflare-ready"]} />
          <StackBox label="Observability" items={["Logfire", "Sentry", "GitHub Actions CI"]} />
          <StackBox label="Security" items={["pip-audit", "Magic-byte validation", "Pillow re-encode"]} />
          <StackBox label="Dev approach" items={["Cursor", "Claude Code", "Codex"]} />
        </div>
      </Section>

      {/* ── Transferable workflow ────────────────────────────────── */}
      <Section eyebrow="Why this matters" title="A workflow, not a feature">
        <div className="rounded-3xl border border-stone-200/80 bg-gradient-to-br from-warm/10 via-white/60 to-white/40 p-7 md:p-10">
          <p className="text-xs font-bold uppercase tracking-wider text-warm-ink/70">
            Transferable case · Insurance claims intake
          </p>
          <h3 className="mt-2 font-display text-2xl font-semibold tracking-tight text-stone-900 md:text-3xl">
            The same pipeline runs on a claim form.
          </h3>
          <p className="mt-4 max-w-3xl text-[16px] leading-[1.75] text-stone-700">
            Swap the input (handwritten claim form) and the schema (claim
            date, claimant, claim type, declared amount, supporting documents
            flagged for review). Everything else is the same code path: the
            Gemini call, the structured output, the validation layer, the
            storage model, the observability. Intake time drops from
            minutes of manual data entry to seconds of human review, and
            every claim arrives with an audit trail attached.
          </p>
          <p className="mt-3 max-w-3xl text-[16px] leading-[1.75] text-stone-700">
            The same shape applies to meeting notes → action items, policy
            documents → compliance checklists, and support tickets →
            categorised triage queues. The hard part is never the model. It
            is the schema, the validation, and the workflow around it.
          </p>
        </div>
      </Section>

      {/* ── My role ──────────────────────────────────────────────── */}
      <Section eyebrow="Honest framing" title="My role">
        <p className="max-w-3xl text-[16px] leading-[1.75] text-stone-700">
          I led product decisions and workflow design; implementation was
          AI-assisted with Cursor, Claude Code and Codex. In practice that
          meant:
        </p>
        <ul className="mt-6 grid grid-cols-1 gap-3 text-[15px] leading-[1.7] text-stone-700 md:grid-cols-2">
          {[
            "Defined the product problem and the user workflow end-to-end.",
            "Designed the data model: typed content blocks, multi-focus extraction, structured Gemini output.",
            "Wrote the prompt architecture, including the security directive and per-focus extraction strategy.",
            "Directed and reviewed AI-assisted code generation across frontend, backend and SQL.",
            "Tested and iterated through real classroom use with my own French course.",
            "Made the calls on what to drop; half-built scope is tax on every future change.",
          ].map((line) => (
            <li key={line} className="relative pl-5">
              <span className="absolute left-0 top-[0.7em] h-1.5 w-1.5 rounded-full bg-stone-400" />
              {line}
            </li>
          ))}
        </ul>
      </Section>

      {/* ── CV-ready summary ─────────────────────────────────────── */}
      <Section eyebrow="For your tracker" title="CV-ready summary">
        <div className="rounded-2xl border border-stone-200/70 bg-white/60 p-6 md:p-8">
          <pre className="whitespace-pre-wrap font-serif text-[15px] leading-[1.7] text-stone-800">
{CV_SUMMARY}
          </pre>
          <div className="mt-5">
            <CopyButton text={CV_SUMMARY} label="Copy summary" />
          </div>
        </div>
      </Section>

      {/* ── Contact ──────────────────────────────────────────────── */}
      <Section eyebrow="Talk to me" title="Demo available on request">
        <p className="max-w-3xl text-[16px] leading-[1.75] text-stone-700">
          The full app stays private to protect personal learning data; no
          public login. Happy to give a guided walkthrough on a 20-minute
          call, or share read-only access for a hiring loop.
        </p>
        <div className="mt-6 flex flex-wrap gap-3">
          <a
            href={site.demoMailto("French AI Learning App")}
            className="inline-flex items-center gap-2 rounded-xl bg-accent-deep px-4 py-2 text-sm font-semibold text-white transition hover:bg-accent-darker"
          >
            <Mail className="h-4 w-4" />
            Request demo
          </a>
          <a
            href={site.cvPdf}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-2 rounded-xl border border-stone-300/70 bg-white/60 px-4 py-2 text-sm font-semibold text-stone-700 transition hover:bg-white"
          >
            <FileDown className="h-4 w-4" />
            Download CV (PDF)
          </a>
          <a
            href={site.github}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-2 rounded-xl border border-stone-300/70 bg-white/60 px-4 py-2 text-sm font-semibold text-stone-700 transition hover:bg-white"
          >
            <Github className="h-4 w-4" />
            GitHub profile
          </a>
          <a
            href={site.linkedin}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-2 rounded-xl border border-stone-300/70 bg-white/60 px-4 py-2 text-sm font-semibold text-stone-700 transition hover:bg-white"
          >
            <Linkedin className="h-4 w-4" />
            LinkedIn
          </a>
        </div>
      </Section>

      {/* ── Footer ────────────────────────────────────────────────── */}
      <footer className="mt-24 border-t border-stone-200/70 pt-8 text-sm text-stone-600 md:mt-32">
        <p>
          {site.name} · {site.location} · {site.email}
        </p>
      </footer>
    </main>
  );
}

/**
 * Phone-recorded lifecycle demo — autoplays muted on loop so a
 * recruiter sees motion within the first viewport, on phone or
 * desktop. `playsInline` is required for iOS Safari autoplay to
 * work without forcing fullscreen.
 */
function DemoVideo() {
  return (
    <figure className="mt-12">
      <div className="mx-auto max-w-md overflow-hidden rounded-[2.25rem] border border-stone-200/70 bg-stone-900 shadow-[0_30px_80px_rgba(28,26,22,0.18)]">
        <video
          src="/case-studies/french-ai/demo-mobile.mp4"
          className="block h-auto w-full"
          autoPlay
          muted
          loop
          playsInline
          preload="metadata"
          aria-label="Phone recording of the full scan-to-card lifecycle: photographing handwritten classroom notes and receiving a structured vocabulary card from the AI scanner."
        />
      </div>
      <figcaption className="mt-3 text-center text-[14px] leading-[1.55] text-stone-600">
        60-second phone recording: handwritten page, photo, AI scan, card.
        Real time, no cuts.
      </figcaption>
    </figure>
  );
}

/**
 * Hero before/after — two side-by-side images carrying the whole
 * pitch in one glance. Handwritten notes on the left, structured
 * vocabulary card on the right. Page-specific (only French uses
 * this layout) so it stays inline rather than in components/case-study.
 */
function BeforeAfterSlot({
  kind,
  caption,
}: {
  kind: "before" | "after";
  caption: string;
}) {
  const label = kind === "before" ? "BEFORE" : "AFTER";
  const filename = kind === "before" ? "notes-before.jpg" : "card-after.jpg";
  const dims =
    kind === "before"
      ? { w: 1999, h: 1499 } // notes — 4:3 landscape
      : { w: 1302, h: 1236 }; // card — near-square portrait
  const alt =
    kind === "before"
      ? "A page of handwritten French class notes: vocabulary, expressions and full sentences for the topic 'Se décrire professionnellement'."
      : "Generated vocabulary card from the same notes: 14 entries with French definitions, English translations and part-of-speech tags.";
  const frame =
    kind === "before"
      ? "border-stone-300/80 bg-cream-deep/40"
      : "border-accent/30 bg-gradient-to-br from-accent/[0.06] via-white/40 to-white/40";
  return (
    <figure>
      <span className="inline-flex rounded-full border border-stone-300/70 bg-white/70 px-3 py-1 text-[10.5px] font-bold uppercase tracking-[0.18em] text-stone-600">
        {label}
      </span>
      <div className={`relative mt-3 overflow-hidden rounded-3xl border ${frame}`}>
        <Image
          src={`/case-studies/french-ai/${filename}`}
          alt={alt}
          width={dims.w}
          height={dims.h}
          sizes="(min-width: 768px) 50vw, 100vw"
          className="block h-auto w-full"
          priority={kind === "before"}
        />
      </div>
      <figcaption className="mt-3 text-[14px] leading-[1.55] text-stone-600">
        {caption}
      </figcaption>
    </figure>
  );
}
