/**
 * Case study — French AI Learning App.
 *
 * Public, recruiter-facing deep dive on the private French learning
 * web app. The page is structured to be skimmed in 30 seconds (hero
 * + workflow) and then read in 3 minutes (decisions, production
 * concerns, transferable workflow).
 *
 * SCREENSHOT PLACEHOLDERS — every `<ImageSlot>` below marks a spot
 * where a real .png from /public/case-studies/french-ai/ should be
 * dropped. The labelled placeholder boxes intentionally render
 * even without files so the layout stays intact during edits.
 */

import type { Metadata } from "next";
import Link from "next/link";
import {
  ArrowLeft,
  Camera,
  Sparkles,
  FileText,
  BookOpenCheck,
  Printer,
  Mail,
  Github,
  Linkedin,
  Shield,
  ScanLine,
  Database,
  Eye,
} from "lucide-react";
import { Hairline, Section } from "@/components/section";
import { CopyButton } from "@/components/copy-button";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "French AI Learning App — Case Study · Jakub Sykulski",
  description:
    "Handwritten classroom notes → structured vocabulary cards via Gemini. A case study in AI-assisted product prototyping.",
  robots: { index: false, follow: false },
};

const CV_SUMMARY = `AI-assisted Learning & Knowledge Workflow Prototype
Designed and built a private AI-assisted web application that converts scanned French classroom notes into structured vocabulary cards, explanations and print-ready revision materials using the Gemini API. Defined the product workflow, data model and prompt architecture; implementation was AI-assisted with Cursor, Claude Code and Codex on Next.js, FastAPI and Supabase. The underlying scan-to-structured-knowledge pipeline is directly transferable to claims intake, meeting notes and policy-document processing.`;

export default function CaseStudy() {
  return (
    <main className="mx-auto max-w-5xl px-6 py-10 md:px-10 md:py-16">
      {/* ── Back link ─────────────────────────────────────────────── */}
      <Link
        href="/"
        className="inline-flex items-center gap-1.5 text-sm font-medium text-stone-600 transition hover:text-stone-900"
      >
        <ArrowLeft className="h-4 w-4" />
        Back to portfolio
      </Link>

      {/* ── Hero ──────────────────────────────────────────────────── */}
      <header className="mt-10">
        <p className="text-[0.78rem] font-bold uppercase tracking-[0.14em] text-stone-500">
          Case study · Education · Knowledge workflows
        </p>
        <h1
          className="shimmer mt-4 text-[clamp(2.25rem,6.5vw,4.25rem)] font-extrabold leading-[1.05] tracking-tight"
          style={{ fontFamily: "var(--font-display)" }}
        >
          Turning handwritten classroom notes
          <br />
          into structured learning material.
        </h1>
        <p className="mt-5 max-w-3xl text-[17px] leading-[1.7] text-stone-700 md:text-lg">
          A private web app that scans French classroom notes and returns
          clean vocabulary cards, grammar explanations, conjugation tables and
          print-ready revision sheets — generated by the Gemini API and
          stored as structured, reusable data.
        </p>

        <div className="mt-6 flex flex-wrap gap-3">
          <a
            href={site.demoMailto("French AI Learning App")}
            className="inline-flex items-center gap-2 rounded-xl bg-[#1a2f73] px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-[#13245a]"
          >
            <Mail className="h-4 w-4" />
            Request demo access
          </a>
          <a
            href="#architecture"
            className="inline-flex items-center gap-2 rounded-xl border border-stone-300/70 bg-white/60 px-4 py-2 text-sm font-semibold text-stone-700 transition hover:bg-white"
          >
            Jump to architecture
          </a>
        </div>

        {/* Before / After visual — the whole pitch in one image pair. */}
        <div className="mt-12 grid grid-cols-1 gap-6 md:grid-cols-2">
          <BeforeAfterSlot
            kind="before"
            caption="A page of handwritten French class notes — what the learner brings in."
          />
          <BeforeAfterSlot
            kind="after"
            caption="A structured vocabulary card — what the app returns, ready for revision."
          />
        </div>
      </header>

      <Hairline />

      {/* ── The problem ──────────────────────────────────────────── */}
      <Section eyebrow="Context" title="The problem">
        <div className="grid gap-6 text-[16px] leading-[1.75] text-stone-700 md:grid-cols-3">
          <p>
            Handwritten notes are messy: vocabulary is scattered across
            margins, grammar rules mix with examples, and translations live
            on a different page than the words they explain.
          </p>
          <p>
            Building clean revision material by hand is a 20-minute chore
            after every class — exactly when motivation is lowest. Most
            learners skip it. So do their classmates.
          </p>
          <p>
            The app removes the chore: photograph the page, choose what to
            extract, and get a structured card back in seconds — searchable,
            printable, and shareable with the class group.
          </p>
        </div>
      </Section>

      {/* ── Workflow ─────────────────────────────────────────────── */}
      <Section eyebrow="How it works" title="The workflow">
        <ol className="grid grid-cols-1 gap-4 md:grid-cols-5">
          <WorkflowStep n={1} icon={<Camera className="h-5 w-5" />} label="Photo" sub="Mobile or desktop upload" />
          <WorkflowStep n={2} icon={<Sparkles className="h-5 w-5" />} label="Gemini" sub="Multi-focus extraction" />
          <WorkflowStep n={3} icon={<FileText className="h-5 w-5" />} label="Structured JSON" sub="Validated server-side" />
          <WorkflowStep n={4} icon={<BookOpenCheck className="h-5 w-5" />} label="Stored card" sub="Searchable, shareable" />
          <WorkflowStep n={5} icon={<Printer className="h-5 w-5" />} label="Revise / print" sub="Spaced repetition ready" />
        </ol>
      </Section>

      {/* ── Product tour ─────────────────────────────────────────── */}
      <Section eyebrow="The product" title="What it does">
        <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
          <ImageSlot
            label="Home dashboard"
            caption="Three entry points: weekly course path, revision library, scanner."
            filename="home.png"
          />
          <ImageSlot
            label="Scanner upload"
            caption="Pick focuses (vocabulary, grammar, conjugation, translation) and upload."
            filename="scanner.png"
          />
          <ImageSlot
            label="Generated vocabulary card"
            caption="Each word: gender, translation, example sentence, conjugation when relevant."
            filename="card.png"
          />
          <ImageSlot
            label="Revision library"
            caption="Grammar, conjugation and curated examples — one searchable library."
            filename="revision.png"
          />
          <ImageSlot
            label="Weekly course path"
            caption="Sections in order, mirroring the rhythm of the actual class."
            filename="parcours.png"
            wide
          />
        </div>
      </Section>

      {/* ── Decisions ────────────────────────────────────────────── */}
      <Section eyebrow="The hard parts" title="Decisions & trade-offs">
        <div className="grid grid-cols-1 gap-5 md:grid-cols-2">
          <DecisionCard
            title="Gemini over OpenAI"
            body="Gemini 2.5 and 3 handle multimodal input (image + text) natively with structured JSON output via response_schema. Cheaper per call at our volume, and the schema-enforced output meant less brittle parsing on the backend."
          />
          <DecisionCard
            title="response_schema, not free-text JSON"
            body="Free-text JSON output drifts: keys disappear, types change. Forcing Gemini through a strict schema kills that whole class of bugs and acts as a second line of defence against prompt injection (the model can't easily exfiltrate fields that aren't in the schema)."
          />
          <DecisionCard
            title="Typed content blocks, not MDX"
            body="Course content lives as typed JSON blocks (heading, paragraph, vocab, example, quiz) — not freeform Markdown. Editors stay safe, admin UI can render previews, and the same blocks render to mobile, print, and revision in three styles."
          />
          <DecisionCard
            title="FastAPI, not Next.js API routes"
            body="The AI pipeline (image validation, Gemini calls, post-processing) is enough work that I wanted a typed Python service with proper test coverage, separate from the UI deploy. Render auto-deploys the backend; Vercel handles the frontend. Two failure modes, isolated."
          />
          <DecisionCard
            title="Multi-focus, not one-shot"
            body="Users pick which sections they want (vocabulary, grammar, conjugation, translation). Each focus is an independent extraction with its own validation. Smaller prompts, better focus quality, and one focus failing doesn't sink the whole scan."
          />
        </div>
      </Section>

      {/* ── Production-aware prototyping ─────────────────────────── */}
      <Section
        eyebrow="What sets this apart"
        title="Production-aware prototyping"
      >
        <p className="max-w-3xl text-[16px] leading-[1.75] text-stone-700">
          Most AI-assisted prototypes ship the happy path and call it done.
          This one was built as if real users (my classmates) depended on it,
          which meant treating security, observability and dependency
          hygiene as first-class concerns — not afterthoughts.
        </p>
        <ul className="mt-8 grid grid-cols-1 gap-5 md:grid-cols-2">
          <ProductionCard
            icon={<Shield />}
            title="Defence in depth against prompt injection"
            body="Three layers in the Gemini pipeline: a security directive at the top of the system prompt, response_schema constraining output shape, and URL redaction against an allowlist before content reaches the model. Each layer can fail and the others still catch the attack."
          />
          <ProductionCard
            icon={<ScanLine />}
            title="Image validation by magic bytes"
            body="Uploaded images are checked by magic bytes — not the multipart Content-Type the browser claims. Anything not in the explicit allowlist (PNG, JPEG, HEIC, WebP) is rejected, then re-encoded through Pillow before reaching the AI. Polyglot files don't get past the gate."
          />
          <ProductionCard
            icon={<Database />}
            title="Row Level Security as fallback"
            body="The backend uses Supabase service-role and filters by user at the service layer. Row Level Security at the Postgres layer is enabled regardless — so a leaked anon key, or a future direct PostgREST hit, still can't cross user boundaries."
          />
          <ProductionCard
            icon={<Eye />}
            title="Observability + dependency audit in CI"
            body="Logfire spans on every request, Sentry on uncaught errors with PII off. CI runs pip-audit on every backend build and npm ci --ignore-scripts to defuse postinstall worms. Dependabot opens PRs weekly; major bumps stay manual."
          />
        </ul>
      </Section>

      {/* ── Architecture ─────────────────────────────────────────── */}
      <Section
        eyebrow="Architecture"
        title="Stack"
        className="scroll-mt-12"
      >
        <div id="architecture" className="grid grid-cols-2 gap-5 md:grid-cols-4">
          <StackBox label="Frontend" items={["Next.js 16", "TypeScript", "Tailwind 4"]} />
          <StackBox label="Backend" items={["FastAPI", "Python 3.12", "Pydantic v2"]} />
          <StackBox label="Data & auth" items={["Supabase Postgres", "Row Level Security", "Postgres FTS"]} />
          <StackBox label="AI" items={["Gemini 2.5 / 3", "response_schema", "Multi-focus prompts"]} />
          <StackBox label="Deploy" items={["Vercel (FE)", "Render (BE)", "Cloudflare-ready"]} />
          <StackBox label="Observability" items={["Logfire", "Sentry", "GitHub Actions CI"]} />
          <StackBox label="Security" items={["pip-audit", "Magic-byte validation", "Pillow re-encode"]} />
          <StackBox label="Dev approach" items={["Cursor", "Claude Code", "Codex"]} />
        </div>
      </Section>

      {/* ── Transferable workflow ────────────────────────────────── */}
      <Section eyebrow="Why this matters" title="A workflow, not a feature">
        <div className="rounded-3xl border border-stone-200/80 bg-gradient-to-br from-[#efb84a]/[0.10] via-white/60 to-white/40 p-7 md:p-10">
          <p
            className="text-xs font-bold uppercase tracking-wider text-[#7a4f10]/70"
          >
            Transferable case · Insurance claims intake
          </p>
          <h3
            className="mt-2 text-2xl font-semibold tracking-tight text-stone-900 md:text-3xl"
            style={{ fontFamily: "var(--font-display)" }}
          >
            The same pipeline runs on a claim form.
          </h3>
          <p className="mt-4 max-w-3xl text-[16px] leading-[1.75] text-stone-700">
            Swap the input (handwritten claim form) and the schema (claim
            date, claimant, claim type, declared amount, supporting documents
            flagged for review). Everything else — the Gemini call, the
            structured output, the validation layer, the storage model, the
            observability — is the same code path. Intake time drops from
            minutes of manual data entry to seconds of human review, and
            every claim arrives with an audit trail attached.
          </p>
          <p className="mt-3 max-w-3xl text-[16px] leading-[1.75] text-stone-700">
            The same shape applies to meeting notes → action items, policy
            documents → compliance checklists, and support tickets →
            categorised triage queues. The hard part is never the model — it
            is the schema, the validation, and the workflow around it.
          </p>
        </div>
      </Section>

      {/* ── My role ──────────────────────────────────────────────── */}
      <Section eyebrow="Honest framing" title="My role">
        <p className="max-w-3xl text-[16px] leading-[1.75] text-stone-700">
          I led product decisions and workflow design; implementation was
          AI-assisted with Cursor, Claude Code and Codex. In practice that
          meant:
        </p>
        <ul className="mt-6 grid grid-cols-1 gap-3 text-[15px] leading-[1.7] text-stone-700 md:grid-cols-2">
          {[
            "Defined the product problem and the user workflow end-to-end.",
            "Designed the data model — typed content blocks, multi-focus extraction, structured Gemini output.",
            "Wrote the prompt architecture, including the security directive and per-focus extraction strategy.",
            "Directed and reviewed AI-assisted code generation across frontend, backend and SQL.",
            "Tested, iterated and shipped through real classroom use with my own French course.",
            "Made the calls on what to drop — half-built scope is tax on every future change.",
          ].map((line) => (
            <li key={line} className="relative pl-5">
              <span className="absolute left-0 top-[0.7em] h-1.5 w-1.5 rounded-full bg-stone-400" />
              {line}
            </li>
          ))}
        </ul>
      </Section>

      {/* ── CV-ready summary ─────────────────────────────────────── */}
      <Section eyebrow="For your tracker" title="CV-ready summary">
        <div className="rounded-2xl border border-stone-200/70 bg-white/60 p-6 md:p-8">
          <pre className="whitespace-pre-wrap font-serif text-[15px] leading-[1.7] text-stone-800">
{CV_SUMMARY}
          </pre>
          <div className="mt-5">
            <CopyButton text={CV_SUMMARY} label="Copy summary" />
          </div>
        </div>
      </Section>

      {/* ── Contact ──────────────────────────────────────────────── */}
      <Section eyebrow="Talk to me" title="Demo available on request">
        <p className="max-w-3xl text-[16px] leading-[1.75] text-stone-700">
          The full app stays private to protect personal learning data — no
          public login. Happy to give a guided walkthrough on a 20-minute
          call, or share read-only access for a hiring loop.
        </p>
        <div className="mt-6 flex flex-wrap gap-3">
          <a
            href={site.demoMailto("French AI Learning App")}
            className="inline-flex items-center gap-2 rounded-xl bg-[#1a2f73] px-4 py-2 text-sm font-semibold text-white transition hover:bg-[#13245a]"
          >
            <Mail className="h-4 w-4" />
            Request demo
          </a>
          <a
            href={site.github}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-2 rounded-xl border border-stone-300/70 bg-white/60 px-4 py-2 text-sm font-semibold text-stone-700 transition hover:bg-white"
          >
            <Github className="h-4 w-4" />
            GitHub profile
          </a>
          <a
            href={site.linkedin}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-2 rounded-xl border border-stone-300/70 bg-white/60 px-4 py-2 text-sm font-semibold text-stone-700 transition hover:bg-white"
          >
            <Linkedin className="h-4 w-4" />
            LinkedIn
          </a>
        </div>
      </Section>

      {/* ── Footer ────────────────────────────────────────────────── */}
      <footer className="mt-24 border-t border-stone-200/70 pt-8 text-sm text-stone-600 md:mt-32">
        <p>
          {site.name} · {site.location} · {site.email}
        </p>
      </footer>
    </main>
  );
}

/* ── Building blocks ──────────────────────────────────────────────── */

function WorkflowStep({
  n,
  icon,
  label,
  sub,
}: {
  n: number;
  icon: React.ReactNode;
  label: string;
  sub: string;
}) {
  return (
    <li className="relative rounded-2xl border border-stone-200/80 bg-white/60 p-5">
      <span className="absolute right-3 top-3 text-[11px] font-bold text-stone-300">
        0{n}
      </span>
      <div className="grid h-10 w-10 place-items-center rounded-xl bg-[#5d6fff]/10 text-[#1a2f73] ring-1 ring-[#5d6fff]/20">
        {icon}
      </div>
      <p
        className="mt-3 text-base font-semibold text-stone-900"
        style={{ fontFamily: "var(--font-display)" }}
      >
        {label}
      </p>
      <p className="mt-1 text-[13px] text-stone-600">{sub}</p>
    </li>
  );
}

function DecisionCard({ title, body }: { title: string; body: string }) {
  return (
    <div className="rounded-2xl border border-stone-200/80 bg-white/60 p-6">
      <p
        className="text-base font-semibold text-stone-900"
        style={{ fontFamily: "var(--font-display)" }}
      >
        {title}
      </p>
      <p className="mt-2 text-[15px] leading-[1.7] text-stone-700">{body}</p>
    </div>
  );
}

function ProductionCard({
  icon,
  title,
  body,
}: {
  icon: React.ReactNode;
  title: string;
  body: string;
}) {
  return (
    <li className="rounded-2xl border border-stone-200/80 bg-white/60 p-6">
      <div className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-500/10 text-emerald-800 ring-1 ring-emerald-500/20">
        {icon}
      </div>
      <p
        className="mt-3 text-base font-semibold text-stone-900"
        style={{ fontFamily: "var(--font-display)" }}
      >
        {title}
      </p>
      <p className="mt-2 text-[15px] leading-[1.7] text-stone-700">{body}</p>
    </li>
  );
}

function StackBox({ label, items }: { label: string; items: string[] }) {
  return (
    <div className="rounded-2xl border border-stone-200/80 bg-white/60 p-5">
      <p className="text-[11px] font-bold uppercase tracking-wider text-stone-500">
        {label}
      </p>
      <ul className="mt-3 space-y-1 text-[14px] text-stone-700">
        {items.map((i) => (
          <li key={i}>{i}</li>
        ))}
      </ul>
    </div>
  );
}

/**
 * Image placeholder — shows a clearly-labelled box where a real .png
 * will live. Swap the inner content for <Image src=... /> from
 * next/image once you drop the screenshot at the indicated path.
 */
function ImageSlot({
  label,
  caption,
  filename,
  wide,
}: {
  label: string;
  caption: string;
  filename: string;
  wide?: boolean;
}) {
  return (
    <figure className={wide ? "md:col-span-2" : ""}>
      {/* SCREENSHOT: /public/case-studies/french-ai/{filename} */}
      <div className="grid aspect-[4/3] place-items-center overflow-hidden rounded-2xl border border-dashed border-stone-300/80 bg-[#f3ecdf]/60 text-center">
        <div className="px-6">
          <p
            className="text-base font-semibold text-stone-800"
            style={{ fontFamily: "var(--font-display)" }}
          >
            {label}
          </p>
          <p className="mt-1 text-xs text-stone-500">
            Drop screenshot at <code className="rounded bg-white/70 px-1.5 py-0.5 text-[11px]">/public/case-studies/french-ai/{filename}</code>
          </p>
        </div>
      </div>
      <figcaption className="mt-2 text-[13px] leading-[1.55] text-stone-600">
        {caption}
      </figcaption>
    </figure>
  );
}

/**
 * Hero before/after — same idea as ImageSlot, but two side-by-side
 * boxes carrying the entire pitch in one glance.
 */
function BeforeAfterSlot({
  kind,
  caption,
}: {
  kind: "before" | "after";
  caption: string;
}) {
  const label = kind === "before" ? "BEFORE" : "AFTER";
  const filename = kind === "before" ? "notes-before.jpg" : "card-after.png";
  const accent =
    kind === "before"
      ? "border-stone-300/80 bg-[#f3ecdf]/70"
      : "border-[#5d6fff]/30 bg-gradient-to-br from-[#5d6fff]/[0.08] via-white/60 to-white/40";
  return (
    <figure>
      {/* SCREENSHOT: /public/case-studies/french-ai/{filename} */}
      <div
        className={`grid aspect-[4/3] place-items-center overflow-hidden rounded-3xl border border-dashed ${accent} text-center`}
      >
        <div className="px-6">
          <p className="text-[11px] font-bold uppercase tracking-[0.18em] text-stone-500">
            {label}
          </p>
          <p
            className="mt-2 text-lg font-semibold text-stone-800"
            style={{ fontFamily: "var(--font-display)" }}
          >
            {kind === "before"
              ? "Handwritten classroom notes"
              : "Structured vocabulary card"}
          </p>
          <p className="mt-1 text-xs text-stone-500">
            Drop at <code className="rounded bg-white/70 px-1.5 py-0.5 text-[11px]">/public/case-studies/french-ai/{filename}</code>
          </p>
        </div>
      </div>
      <figcaption className="mt-3 text-[14px] leading-[1.55] text-stone-600">
        {caption}
      </figcaption>
    </figure>
  );
}
